---
- name: Creating groups
  group: name="{{item}}"
  with_items: groups_to_create
  tags: ['users','groups','configuration']

- name: Per-user group creation
  group: name="{{item.username}}"
         gid="{{item.gid if item.gid is defined else item.uid}}"
  with_items: users
  when: users_create_per_user_group
  tags: ['users','configuration']

- name: User creation
  user: name="{{item.username}}"
        group="{{item.username if users_create_per_user_group
            else users_group}}"
        groups="{{item.groups | join(',')}}"
        shell={{item.shell if item.shell is defined else users_default_shell}}
        password="{{item.password if item.password is defined else '!'}}"
        comment="{{item.name if item.name is defined else ''}}"
        uid="{{item.uid}}"
        createhome="{{'yes' if users_create_homedirs else 'no'}}"
        update_password="{{'always' if users_always_update_passwd else 'on_create'}}"
  with_items: users
  tags: ['users','configuration']

- name: SSH keys
  authorized_key: user="{{item.0.username}}" key="{{item.1}}" key_options="{{ options_tunnel_only if item.0.tunnel_only is defined else '' }}" 
  with_subelements:
    - users
    - ssh_key
  tags: ['users','configuration']

- name: Deleted user removal
  user: name="{{item.username}}" state=absent
  with_items: users_deleted
  tags: ['users','configuration']

- name: Deleted per-user group removal
  group: name="{{item.username}}" state=absent
  with_items: users_deleted
  when: users_create_per_user_group
  tags: ['users','configuration']
